*** Starting uWSGI 2.0.26 (64bit) on [Wed Jul  3 15:05:39 2024] ***
compiled with version: 13.2.0 on 03 July 2024 14:58:40
os: Linux-6.8.0-1009-aws #9-Ubuntu SMP Fri May 17 14:39:23 UTC 2024
nodename: ip-172-31-4-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ubuntu/likelion_team5/likelion_inha_team5/likelion_inha_team5
writing pidfile to /tmp/project-master.pid
detected binary path: /home/ubuntu/dasol/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ubuntu/likelion_team5/likelion_inha_team5/likelion_inha_team5
your processes number limit is 3769
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
Python version: 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]
!!! Python Home is not a directory: /home/ubuntu/dasol/uwsgi.sock !!!
Set PythonHome to /home/ubuntu/dasol/uwsgi.sock
Python path configuration:
  PYTHONHOME = '/home/ubuntu/dasol/uwsgi.sock'
  PYTHONPATH = (not set)
  program name = '/home/ubuntu/dasol/uwsgi.sock/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/home/ubuntu/dasol/uwsgi.sock/lib/python3.12'
  sys._base_executable = '/home/ubuntu/dasol/uwsgi.sock/bin/python'
  sys.base_prefix = '/home/ubuntu/dasol/uwsgi.sock'
  sys.base_exec_prefix = '/home/ubuntu/dasol/uwsgi.sock'
  sys.platlibdir = 'lib'
  sys.executable = '/home/ubuntu/dasol/uwsgi.sock/bin/python'
  sys.prefix = '/home/ubuntu/dasol/uwsgi.sock'
  sys.exec_prefix = '/home/ubuntu/dasol/uwsgi.sock'
  sys.path = [
    '/home/ubuntu/dasol/uwsgi.sock/lib/python312.zip',
    '/home/ubuntu/dasol/uwsgi.sock/lib/python3.12',
    '/home/ubuntu/dasol/uwsgi.sock/lib/python3.12/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007e4f96a67740 (most recent call first):
  <no Python frame>
*** Starting uWSGI 2.0.26 (64bit) on [Wed Jul  3 15:17:52 2024] ***
compiled with version: 13.2.0 on 03 July 2024 14:58:40
os: Linux-6.8.0-1009-aws #9-Ubuntu SMP Fri May 17 14:39:23 UTC 2024
nodename: ip-172-31-4-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ubuntu/likelion_team5/likelion_inha_team5/likelion_inha_team5
writing pidfile to /tmp/project-master.pid
detected binary path: /home/ubuntu/dasol/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ubuntu/likelion_team5/likelion_inha_team5/likelion_inha_team5
your processes number limit is 3769
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/likelion_team5/likelion_inha_team5/likelion_inha_team5/uwsgi.sock fd 3
Python version: 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]
PEP 405 virtualenv detected: /home/ubuntu/dasol
Set PythonHome to /home/ubuntu/dasol
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7e7d2a29ff68
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7e7d2a29ff68 pid: 4397 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4397)
spawned uWSGI worker 1 (pid: 4398, cores: 1)
Not Found: /
[pid: 4398|app: 0|req: 1/1] 218.159.222.184 () {44 vars in 850 bytes} [Thu Jul  4 00:18:24 2024] GET / => generated 5544 bytes in 64 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 4398|app: 0|req: 2/2] 218.159.222.184 () {42 vars in 773 bytes} [Thu Jul  4 00:18:25 2024] GET /favicon.ico => generated 5595 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 3/3] 218.159.222.184 () {42 vars in 829 bytes} [Thu Jul  4 00:18:29 2024] GET /admin => generated 0 bytes in 6 msecs (HTTP/1.1 301) 5 headers in 197 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 4/4] 218.159.222.184 () {42 vars in 831 bytes} [Thu Jul  4 00:18:29 2024] GET /admin/ => generated 11794 bytes in 72 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
Not Found: /static/admin/css/base.css
[pid: 4398|app: 0|req: 5/5] 218.159.222.184 () {42 vars in 761 bytes} [Thu Jul  4 00:18:29 2024] GET /static/admin/css/base.css => generated 5906 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/dark_mode.css
[pid: 4398|app: 0|req: 6/6] 218.159.222.184 () {42 vars in 771 bytes} [Thu Jul  4 00:18:30 2024] GET /static/admin/css/dark_mode.css => generated 5926 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/nav_sidebar.css
[pid: 4398|app: 0|req: 7/7] 218.159.222.184 () {42 vars in 775 bytes} [Thu Jul  4 00:18:30 2024] GET /static/admin/css/nav_sidebar.css => generated 5934 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/responsive.css
[pid: 4398|app: 0|req: 8/8] 218.159.222.184 () {42 vars in 773 bytes} [Thu Jul  4 00:18:30 2024] GET /static/admin/css/responsive.css => generated 5930 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/theme.js
[pid: 4398|app: 0|req: 9/9] 218.159.222.184 () {42 vars in 744 bytes} [Thu Jul  4 00:18:30 2024] GET /static/admin/js/theme.js => generated 5902 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/dashboard.css
[pid: 4398|app: 0|req: 10/10] 218.159.222.184 () {42 vars in 771 bytes} [Thu Jul  4 00:18:30 2024] GET /static/admin/css/dashboard.css => generated 5926 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/nav_sidebar.js
[pid: 4398|app: 0|req: 11/11] 218.159.222.184 () {42 vars in 756 bytes} [Thu Jul  4 00:18:30 2024] GET /static/admin/js/nav_sidebar.js => generated 5926 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 12/12] 218.159.222.184 () {42 vars in 833 bytes} [Thu Jul  4 00:18:44 2024] GET /swagger => generated 0 bytes in 6 msecs (HTTP/1.1 301) 5 headers in 199 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 13/13] 218.159.222.184 () {42 vars in 835 bytes} [Thu Jul  4 00:18:44 2024] GET /swagger/ => generated 2417 bytes in 8 msecs (HTTP/1.1 200) 8 headers in 257 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/style.css
[pid: 4398|app: 0|req: 14/14] 218.159.222.184 () {42 vars in 763 bytes} [Thu Jul  4 00:18:44 2024] GET /static/drf-yasg/style.css => generated 5906 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/immutable.min.js
[pid: 4398|app: 0|req: 15/15] 218.159.222.184 () {42 vars in 762 bytes} [Thu Jul  4 00:18:44 2024] GET /static/drf-yasg/immutable.min.js => generated 5934 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/insQ.min.js
[pid: 4398|app: 0|req: 16/16] 218.159.222.184 () {42 vars in 752 bytes} [Thu Jul  4 00:18:44 2024] GET /static/drf-yasg/insQ.min.js => generated 5914 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js
[pid: 4398|app: 0|req: 17/17] 218.159.222.184 () {42 vars in 824 bytes} [Thu Jul  4 00:18:44 2024] GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js => generated 6058 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui.css
[pid: 4398|app: 0|req: 18/18] 218.159.222.184 () {42 vars in 805 bytes} [Thu Jul  4 00:18:44 2024] GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css => generated 5990 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js
[pid: 4398|app: 0|req: 19/19] 218.159.222.184 () {42 vars in 802 bytes} [Thu Jul  4 00:18:44 2024] GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js => generated 6014 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-init.js
[pid: 4398|app: 0|req: 20/20] 218.159.222.184 () {42 vars in 766 bytes} [Thu Jul  4 00:18:44 2024] GET /static/drf-yasg/swagger-ui-init.js => generated 5942 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/favicon-32x32.png
[pid: 4398|app: 0|req: 21/21] 218.159.222.184 () {42 vars in 857 bytes} [Thu Jul  4 00:18:44 2024] GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png => generated 6002 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /accounts/logout/
[pid: 4398|app: 0|req: 22/22] 218.159.222.184 () {44 vars in 926 bytes} [Thu Jul  4 00:18:48 2024] GET /accounts/logout/?next=/swagger/ => generated 5357 bytes in 14 msecs (HTTP/1.1 404) 8 headers in 258 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/bootstrap.min.css
[pid: 4398|app: 0|req: 23/23] 218.159.222.184 () {42 vars in 822 bytes} [Thu Jul  4 00:18:49 2024] GET /static/rest_framework/css/bootstrap.min.css => generated 5978 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
[pid: 4398|app: 0|req: 24/24] 218.159.222.184 () {42 vars in 828 bytes} [Thu Jul  4 00:18:49 2024] GET /static/rest_framework/css/bootstrap-tweaks.css => generated 5990 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/default.css
[pid: 4398|app: 0|req: 25/25] 218.159.222.184 () {42 vars in 810 bytes} [Thu Jul  4 00:18:49 2024] GET /static/rest_framework/css/default.css => generated 5954 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/prettify.css
[pid: 4398|app: 0|req: 26/26] 218.159.222.184 () {42 vars in 812 bytes} [Thu Jul  4 00:18:49 2024] GET /static/rest_framework/css/prettify.css => generated 5958 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/jquery-3.7.1.min.js
[pid: 4398|app: 0|req: 27/27] 218.159.222.184 () {42 vars in 809 bytes} [Thu Jul  4 00:18:49 2024] GET /static/rest_framework/js/jquery-3.7.1.min.js => generated 5982 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/ajax-form.js
[pid: 4398|app: 0|req: 28/28] 218.159.222.184 () {42 vars in 795 bytes} [Thu Jul  4 00:18:49 2024] GET /static/rest_framework/js/ajax-form.js => generated 5954 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/csrf.js
[pid: 4398|app: 0|req: 29/29] 218.159.222.184 () {42 vars in 785 bytes} [Thu Jul  4 00:18:49 2024] GET /static/rest_framework/js/csrf.js => generated 5934 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/bootstrap.min.js
[pid: 4398|app: 0|req: 30/30] 218.159.222.184 () {42 vars in 803 bytes} [Thu Jul  4 00:18:49 2024] GET /static/rest_framework/js/bootstrap.min.js => generated 5970 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/prettify-min.js
[pid: 4398|app: 0|req: 31/31] 218.159.222.184 () {42 vars in 801 bytes} [Thu Jul  4 00:18:49 2024] GET /static/rest_framework/js/prettify-min.js => generated 5966 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/default.js
[pid: 4398|app: 0|req: 32/32] 218.159.222.184 () {42 vars in 791 bytes} [Thu Jul  4 00:18:49 2024] GET /static/rest_framework/js/default.js => generated 5946 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/load-ajax-form.js
[pid: 4398|app: 0|req: 33/33] 218.159.222.184 () {42 vars in 805 bytes} [Thu Jul  4 00:18:49 2024] GET /static/rest_framework/js/load-ajax-form.js => generated 5974 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /accounts/logout/
[pid: 4398|app: 0|req: 34/34] 218.159.222.184 () {44 vars in 920 bytes} [Thu Jul  4 00:18:56 2024] GET /accounts/logout/ => generated 5266 bytes in 7 msecs (HTTP/1.1 404) 8 headers in 258 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/prettify.css
[pid: 4398|app: 0|req: 35/35] 218.159.222.184 () {42 vars in 797 bytes} [Thu Jul  4 00:18:56 2024] GET /static/rest_framework/css/prettify.css => generated 5958 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/bootstrap.min.css
[pid: 4398|app: 0|req: 36/36] 218.159.222.184 () {42 vars in 807 bytes} [Thu Jul  4 00:18:56 2024] GET /static/rest_framework/css/bootstrap.min.css => generated 5978 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/default.css
[pid: 4398|app: 0|req: 37/37] 218.159.222.184 () {42 vars in 795 bytes} [Thu Jul  4 00:18:56 2024] GET /static/rest_framework/css/default.css => generated 5954 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/ajax-form.js
[pid: 4398|app: 0|req: 38/38] 218.159.222.184 () {42 vars in 780 bytes} [Thu Jul  4 00:18:56 2024] GET /static/rest_framework/js/ajax-form.js => generated 5954 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/jquery-3.7.1.min.js
[pid: 4398|app: 0|req: 39/39] 218.159.222.184 () {42 vars in 794 bytes} [Thu Jul  4 00:18:56 2024] GET /static/rest_framework/js/jquery-3.7.1.min.js => generated 5982 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
[pid: 4398|app: 0|req: 40/40] 218.159.222.184 () {42 vars in 813 bytes} [Thu Jul  4 00:18:56 2024] GET /static/rest_framework/css/bootstrap-tweaks.css => generated 5990 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/csrf.js
[pid: 4398|app: 0|req: 41/41] 218.159.222.184 () {42 vars in 770 bytes} [Thu Jul  4 00:18:56 2024] GET /static/rest_framework/js/csrf.js => generated 5934 bytes in 7 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/bootstrap.min.js
[pid: 4398|app: 0|req: 42/42] 218.159.222.184 () {42 vars in 788 bytes} [Thu Jul  4 00:18:56 2024] GET /static/rest_framework/js/bootstrap.min.js => generated 5970 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/prettify-min.js
[pid: 4398|app: 0|req: 43/43] 218.159.222.184 () {42 vars in 786 bytes} [Thu Jul  4 00:18:56 2024] GET /static/rest_framework/js/prettify-min.js => generated 5966 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/default.js
[pid: 4398|app: 0|req: 44/44] 218.159.222.184 () {42 vars in 776 bytes} [Thu Jul  4 00:18:56 2024] GET /static/rest_framework/js/default.js => generated 5946 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/load-ajax-form.js
[pid: 4398|app: 0|req: 45/45] 218.159.222.184 () {42 vars in 790 bytes} [Thu Jul  4 00:18:56 2024] GET /static/rest_framework/js/load-ajax-form.js => generated 5974 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /accounts/logout/
[pid: 4398|app: 0|req: 46/46] 218.159.222.184 () {44 vars in 905 bytes} [Thu Jul  4 00:18:58 2024] GET /accounts/logout/ => generated 5266 bytes in 7 msecs (HTTP/1.1 404) 8 headers in 258 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/bootstrap.min.css
[pid: 4398|app: 0|req: 47/47] 218.159.222.184 () {42 vars in 807 bytes} [Thu Jul  4 00:18:58 2024] GET /static/rest_framework/css/bootstrap.min.css => generated 5978 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/prettify.css
[pid: 4398|app: 0|req: 48/48] 218.159.222.184 () {42 vars in 797 bytes} [Thu Jul  4 00:18:58 2024] GET /static/rest_framework/css/prettify.css => generated 5958 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
[pid: 4398|app: 0|req: 49/49] 218.159.222.184 () {42 vars in 813 bytes} [Thu Jul  4 00:18:58 2024] GET /static/rest_framework/css/bootstrap-tweaks.css => generated 5990 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/jquery-3.7.1.min.js
[pid: 4398|app: 0|req: 50/50] 218.159.222.184 () {42 vars in 794 bytes} [Thu Jul  4 00:18:58 2024] GET /static/rest_framework/js/jquery-3.7.1.min.js => generated 5982 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/default.css
[pid: 4398|app: 0|req: 51/51] 218.159.222.184 () {42 vars in 795 bytes} [Thu Jul  4 00:18:58 2024] GET /static/rest_framework/css/default.css => generated 5954 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/ajax-form.js
[pid: 4398|app: 0|req: 52/52] 218.159.222.184 () {42 vars in 780 bytes} [Thu Jul  4 00:18:58 2024] GET /static/rest_framework/js/ajax-form.js => generated 5954 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/csrf.js
[pid: 4398|app: 0|req: 53/53] 218.159.222.184 () {42 vars in 770 bytes} [Thu Jul  4 00:18:59 2024] GET /static/rest_framework/js/csrf.js => generated 5934 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/bootstrap.min.js
[pid: 4398|app: 0|req: 54/54] 218.159.222.184 () {42 vars in 788 bytes} [Thu Jul  4 00:18:59 2024] GET /static/rest_framework/js/bootstrap.min.js => generated 5970 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/prettify-min.js
[pid: 4398|app: 0|req: 55/55] 218.159.222.184 () {42 vars in 786 bytes} [Thu Jul  4 00:18:59 2024] GET /static/rest_framework/js/prettify-min.js => generated 5966 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/default.js
[pid: 4398|app: 0|req: 56/56] 218.159.222.184 () {42 vars in 776 bytes} [Thu Jul  4 00:18:59 2024] GET /static/rest_framework/js/default.js => generated 5946 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/load-ajax-form.js
[pid: 4398|app: 0|req: 57/57] 218.159.222.184 () {42 vars in 790 bytes} [Thu Jul  4 00:18:59 2024] GET /static/rest_framework/js/load-ajax-form.js => generated 5974 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /accounts/logout/
[pid: 4398|app: 0|req: 58/58] 218.159.222.184 () {44 vars in 906 bytes} [Thu Jul  4 00:19:00 2024] GET /accounts/logout/? => generated 5266 bytes in 7 msecs (HTTP/1.1 404) 8 headers in 258 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/bootstrap.min.css
[pid: 4398|app: 0|req: 59/59] 218.159.222.184 () {42 vars in 808 bytes} [Thu Jul  4 00:19:00 2024] GET /static/rest_framework/css/bootstrap.min.css => generated 5978 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/prettify.css
[pid: 4398|app: 0|req: 60/60] 218.159.222.184 () {42 vars in 798 bytes} [Thu Jul  4 00:19:00 2024] GET /static/rest_framework/css/prettify.css => generated 5958 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
[pid: 4398|app: 0|req: 61/61] 218.159.222.184 () {42 vars in 814 bytes} [Thu Jul  4 00:19:00 2024] GET /static/rest_framework/css/bootstrap-tweaks.css => generated 5990 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/css/default.css
[pid: 4398|app: 0|req: 62/62] 218.159.222.184 () {42 vars in 796 bytes} [Thu Jul  4 00:19:00 2024] GET /static/rest_framework/css/default.css => generated 5954 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/jquery-3.7.1.min.js
[pid: 4398|app: 0|req: 63/63] 218.159.222.184 () {42 vars in 795 bytes} [Thu Jul  4 00:19:00 2024] GET /static/rest_framework/js/jquery-3.7.1.min.js => generated 5982 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/ajax-form.js
[pid: 4398|app: 0|req: 64/64] 218.159.222.184 () {42 vars in 781 bytes} [Thu Jul  4 00:19:00 2024] GET /static/rest_framework/js/ajax-form.js => generated 5954 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/csrf.js
[pid: 4398|app: 0|req: 65/65] 218.159.222.184 () {42 vars in 771 bytes} [Thu Jul  4 00:19:00 2024] GET /static/rest_framework/js/csrf.js => generated 5934 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/bootstrap.min.js
[pid: 4398|app: 0|req: 66/66] 218.159.222.184 () {42 vars in 789 bytes} [Thu Jul  4 00:19:00 2024] GET /static/rest_framework/js/bootstrap.min.js => generated 5970 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/prettify-min.js
[pid: 4398|app: 0|req: 67/67] 218.159.222.184 () {42 vars in 787 bytes} [Thu Jul  4 00:19:00 2024] GET /static/rest_framework/js/prettify-min.js => generated 5966 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/default.js
[pid: 4398|app: 0|req: 68/68] 218.159.222.184 () {42 vars in 777 bytes} [Thu Jul  4 00:19:00 2024] GET /static/rest_framework/js/default.js => generated 5946 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/rest_framework/js/load-ajax-form.js
[pid: 4398|app: 0|req: 69/69] 218.159.222.184 () {42 vars in 791 bytes} [Thu Jul  4 00:19:00 2024] GET /static/rest_framework/js/load-ajax-form.js => generated 5974 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 70/70] 218.159.222.184 () {42 vars in 835 bytes} [Thu Jul  4 00:19:07 2024] GET /swagger/ => generated 2417 bytes in 5 msecs (HTTP/1.1 200) 8 headers in 257 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/style.css
[pid: 4398|app: 0|req: 71/71] 218.159.222.184 () {42 vars in 763 bytes} [Thu Jul  4 00:19:07 2024] GET /static/drf-yasg/style.css => generated 5906 bytes in 7 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js
[pid: 4398|app: 0|req: 72/72] 218.159.222.184 () {42 vars in 824 bytes} [Thu Jul  4 00:19:07 2024] GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js => generated 6058 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/immutable.min.js
[pid: 4398|app: 0|req: 73/73] 218.159.222.184 () {42 vars in 762 bytes} [Thu Jul  4 00:19:07 2024] GET /static/drf-yasg/immutable.min.js => generated 5934 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js
[pid: 4398|app: 0|req: 74/74] 218.159.222.184 () {42 vars in 802 bytes} [Thu Jul  4 00:19:07 2024] GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js => generated 6014 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/insQ.min.js
[pid: 4398|app: 0|req: 75/75] 218.159.222.184 () {42 vars in 752 bytes} [Thu Jul  4 00:19:07 2024] GET /static/drf-yasg/insQ.min.js => generated 5914 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui.css
[pid: 4398|app: 0|req: 76/76] 218.159.222.184 () {42 vars in 805 bytes} [Thu Jul  4 00:19:07 2024] GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css => generated 5990 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-init.js
[pid: 4398|app: 0|req: 77/77] 218.159.222.184 () {42 vars in 766 bytes} [Thu Jul  4 00:19:07 2024] GET /static/drf-yasg/swagger-ui-init.js => generated 5942 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /
[pid: 4398|app: 0|req: 78/78] 218.159.222.184 () {42 vars in 819 bytes} [Thu Jul  4 00:19:11 2024] GET / => generated 5544 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 79/79] 218.159.222.184 () {42 vars in 835 bytes} [Thu Jul  4 00:19:36 2024] GET /swagger/ => generated 2417 bytes in 5 msecs (HTTP/1.1 200) 8 headers in 257 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/style.css
[pid: 4398|app: 0|req: 80/80] 218.159.222.184 () {42 vars in 763 bytes} [Thu Jul  4 00:19:36 2024] GET /static/drf-yasg/style.css => generated 5906 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js
[pid: 4398|app: 0|req: 81/81] 218.159.222.184 () {42 vars in 824 bytes} [Thu Jul  4 00:19:36 2024] GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js => generated 6058 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui.css
[pid: 4398|app: 0|req: 82/82] 218.159.222.184 () {42 vars in 805 bytes} [Thu Jul  4 00:19:36 2024] GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css => generated 5990 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/insQ.min.js
[pid: 4398|app: 0|req: 83/83] 218.159.222.184 () {42 vars in 752 bytes} [Thu Jul  4 00:19:36 2024] GET /static/drf-yasg/insQ.min.js => generated 5914 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/immutable.min.js
[pid: 4398|app: 0|req: 84/84] 218.159.222.184 () {42 vars in 762 bytes} [Thu Jul  4 00:19:36 2024] GET /static/drf-yasg/immutable.min.js => generated 5934 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js
[pid: 4398|app: 0|req: 85/85] 218.159.222.184 () {42 vars in 802 bytes} [Thu Jul  4 00:19:36 2024] GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js => generated 6014 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-init.js
[pid: 4398|app: 0|req: 86/86] 218.159.222.184 () {42 vars in 766 bytes} [Thu Jul  4 00:19:36 2024] GET /static/drf-yasg/swagger-ui-init.js => generated 5942 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 87/87] 218.159.222.184 () {42 vars in 831 bytes} [Thu Jul  4 00:20:42 2024] GET /admin/ => generated 11794 bytes in 15 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
Not Found: /static/admin/js/theme.js
[pid: 4398|app: 0|req: 88/88] 218.159.222.184 () {42 vars in 744 bytes} [Thu Jul  4 00:20:42 2024] GET /static/admin/js/theme.js => generated 5902 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/dark_mode.css
[pid: 4398|app: 0|req: 89/89] 218.159.222.184 () {42 vars in 771 bytes} [Thu Jul  4 00:20:42 2024] GET /static/admin/css/dark_mode.css => generated 5926 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/base.css
[pid: 4398|app: 0|req: 90/90] 218.159.222.184 () {42 vars in 761 bytes} [Thu Jul  4 00:20:42 2024] GET /static/admin/css/base.css => generated 5906 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/nav_sidebar.css
[pid: 4398|app: 0|req: 91/91] 218.159.222.184 () {42 vars in 775 bytes} [Thu Jul  4 00:20:42 2024] GET /static/admin/css/nav_sidebar.css => generated 5934 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/dashboard.css
[pid: 4398|app: 0|req: 92/92] 218.159.222.184 () {42 vars in 771 bytes} [Thu Jul  4 00:20:42 2024] GET /static/admin/css/dashboard.css => generated 5926 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/responsive.css
[pid: 4398|app: 0|req: 93/93] 218.159.222.184 () {42 vars in 773 bytes} [Thu Jul  4 00:20:42 2024] GET /static/admin/css/responsive.css => generated 5930 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/nav_sidebar.js
[pid: 4398|app: 0|req: 94/94] 218.159.222.184 () {42 vars in 756 bytes} [Thu Jul  4 00:20:42 2024] GET /static/admin/js/nav_sidebar.js => generated 5926 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 95/95] 218.159.222.184 () {44 vars in 909 bytes} [Thu Jul  4 00:20:48 2024] GET /admin/workhol/category/ => generated 10349 bytes in 38 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
Not Found: /static/admin/css/base.css
[pid: 4398|app: 0|req: 96/96] 218.159.222.184 () {42 vars in 778 bytes} [Thu Jul  4 00:20:48 2024] GET /static/admin/css/base.css => generated 5906 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/vendor/jquery/jquery.js
[pid: 4398|app: 0|req: 97/97] 218.159.222.184 () {42 vars in 791 bytes} [Thu Jul  4 00:20:48 2024] GET /static/admin/js/vendor/jquery/jquery.js => generated 5962 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/jquery.init.js
[pid: 4398|app: 0|req: 98/98] 218.159.222.184 () {42 vars in 773 bytes} [Thu Jul  4 00:20:48 2024] GET /static/admin/js/jquery.init.js => generated 5926 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/changelists.css
[pid: 4398|app: 0|req: 99/99] 218.159.222.184 () {42 vars in 792 bytes} [Thu Jul  4 00:20:48 2024] GET /static/admin/css/changelists.css => generated 5934 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 100/100] 218.159.222.184 () {42 vars in 739 bytes} [Thu Jul  4 00:20:48 2024] GET /admin/jsi18n/ => generated 9861 bytes in 7 msecs (HTTP/1.1 200) 7 headers in 230 bytes (1 switches on core 0)
Not Found: /static/admin/css/dark_mode.css
[pid: 4398|app: 0|req: 101/101] 218.159.222.184 () {42 vars in 788 bytes} [Thu Jul  4 00:20:48 2024] GET /static/admin/css/dark_mode.css => generated 5926 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/nav_sidebar.css
[pid: 4398|app: 0|req: 102/102] 218.159.222.184 () {42 vars in 792 bytes} [Thu Jul  4 00:20:48 2024] GET /static/admin/css/nav_sidebar.css => generated 5934 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/responsive.css
[pid: 4398|app: 0|req: 103/103] 218.159.222.184 () {42 vars in 790 bytes} [Thu Jul  4 00:20:48 2024] GET /static/admin/css/responsive.css => generated 5930 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/core.js
[pid: 4398|app: 0|req: 104/104] 218.159.222.184 () {42 vars in 759 bytes} [Thu Jul  4 00:20:48 2024] GET /static/admin/js/core.js => generated 5898 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/admin/RelatedObjectLookups.js
[pid: 4398|app: 0|req: 105/105] 218.159.222.184 () {42 vars in 803 bytes} [Thu Jul  4 00:20:48 2024] GET /static/admin/js/admin/RelatedObjectLookups.js => generated 5986 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/actions.js
[pid: 4398|app: 0|req: 106/106] 218.159.222.184 () {42 vars in 765 bytes} [Thu Jul  4 00:20:48 2024] GET /static/admin/js/actions.js => generated 5910 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/urlify.js
[pid: 4398|app: 0|req: 107/107] 218.159.222.184 () {42 vars in 763 bytes} [Thu Jul  4 00:20:48 2024] GET /static/admin/js/urlify.js => generated 5906 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/prepopulate.js
[pid: 4398|app: 0|req: 108/108] 218.159.222.184 () {42 vars in 773 bytes} [Thu Jul  4 00:20:48 2024] GET /static/admin/js/prepopulate.js => generated 5926 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/vendor/xregexp/xregexp.js
[pid: 4398|app: 0|req: 109/109] 218.159.222.184 () {42 vars in 795 bytes} [Thu Jul  4 00:20:49 2024] GET /static/admin/js/vendor/xregexp/xregexp.js => generated 5970 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/theme.js
[pid: 4398|app: 0|req: 110/110] 218.159.222.184 () {42 vars in 761 bytes} [Thu Jul  4 00:20:49 2024] GET /static/admin/js/theme.js => generated 5902 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/nav_sidebar.js
[pid: 4398|app: 0|req: 111/111] 218.159.222.184 () {42 vars in 773 bytes} [Thu Jul  4 00:20:49 2024] GET /static/admin/js/nav_sidebar.js => generated 5926 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/filters.js
[pid: 4398|app: 0|req: 112/112] 218.159.222.184 () {42 vars in 765 bytes} [Thu Jul  4 00:20:49 2024] GET /static/admin/js/filters.js => generated 5910 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/responsive.css
[pid: 4398|app: 0|req: 113/113] 218.159.222.184 () {42 vars in 790 bytes} [Thu Jul  4 00:20:49 2024] GET /static/admin/css/responsive.css => generated 5930 bytes in 7 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 114/114] 218.159.222.184 () {42 vars in 831 bytes} [Thu Jul  4 00:22:31 2024] GET /admin/ => generated 11794 bytes in 15 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
Not Found: /static/admin/css/base.css
[pid: 4398|app: 0|req: 115/115] 218.159.222.184 () {42 vars in 761 bytes} [Thu Jul  4 00:22:31 2024] GET /static/admin/css/base.css => generated 5906 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/dark_mode.css
[pid: 4398|app: 0|req: 116/116] 218.159.222.184 () {42 vars in 771 bytes} [Thu Jul  4 00:22:31 2024] GET /static/admin/css/dark_mode.css => generated 5926 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/theme.js
[pid: 4398|app: 0|req: 117/117] 218.159.222.184 () {42 vars in 744 bytes} [Thu Jul  4 00:22:31 2024] GET /static/admin/js/theme.js => generated 5902 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/responsive.css
[pid: 4398|app: 0|req: 118/118] 218.159.222.184 () {42 vars in 773 bytes} [Thu Jul  4 00:22:31 2024] GET /static/admin/css/responsive.css => generated 5930 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/nav_sidebar.css
[pid: 4398|app: 0|req: 119/119] 218.159.222.184 () {42 vars in 775 bytes} [Thu Jul  4 00:22:31 2024] GET /static/admin/css/nav_sidebar.css => generated 5934 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/dashboard.css
[pid: 4398|app: 0|req: 120/120] 218.159.222.184 () {42 vars in 771 bytes} [Thu Jul  4 00:22:31 2024] GET /static/admin/css/dashboard.css => generated 5926 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/nav_sidebar.js
[pid: 4398|app: 0|req: 121/121] 218.159.222.184 () {42 vars in 756 bytes} [Thu Jul  4 00:22:31 2024] GET /static/admin/js/nav_sidebar.js => generated 5926 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 122/122] 218.159.222.184 () {46 vars in 893 bytes} [Thu Jul  4 00:23:40 2024] GET /admin/ => generated 11794 bytes in 15 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
Not Found: /static/admin/css/dark_mode.css
[pid: 4398|app: 0|req: 123/123] 218.159.222.184 () {46 vars in 833 bytes} [Thu Jul  4 00:23:41 2024] GET /static/admin/css/dark_mode.css => generated 5926 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/base.css
[pid: 4398|app: 0|req: 124/124] 218.159.222.184 () {46 vars in 823 bytes} [Thu Jul  4 00:23:41 2024] GET /static/admin/css/base.css => generated 5906 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/nav_sidebar.css
[pid: 4398|app: 0|req: 125/125] 218.159.222.184 () {46 vars in 837 bytes} [Thu Jul  4 00:23:41 2024] GET /static/admin/css/nav_sidebar.css => generated 5934 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/dashboard.css
[pid: 4398|app: 0|req: 126/126] 218.159.222.184 () {46 vars in 833 bytes} [Thu Jul  4 00:23:41 2024] GET /static/admin/css/dashboard.css => generated 5926 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/responsive.css
[pid: 4398|app: 0|req: 127/127] 218.159.222.184 () {46 vars in 835 bytes} [Thu Jul  4 00:23:41 2024] GET /static/admin/css/responsive.css => generated 5930 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/theme.js
[pid: 4398|app: 0|req: 128/128] 218.159.222.184 () {46 vars in 806 bytes} [Thu Jul  4 00:23:41 2024] GET /static/admin/js/theme.js => generated 5902 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/nav_sidebar.js
[pid: 4398|app: 0|req: 129/129] 218.159.222.184 () {46 vars in 818 bytes} [Thu Jul  4 00:23:41 2024] GET /static/admin/js/nav_sidebar.js => generated 5926 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 130/130] 218.159.222.184 () {42 vars in 835 bytes} [Thu Jul  4 00:23:45 2024] GET /swagger/ => generated 2417 bytes in 5 msecs (HTTP/1.1 200) 8 headers in 257 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/style.css
[pid: 4398|app: 0|req: 131/131] 218.159.222.184 () {42 vars in 763 bytes} [Thu Jul  4 00:23:45 2024] GET /static/drf-yasg/style.css => generated 5906 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/insQ.min.js
[pid: 4398|app: 0|req: 132/132] 218.159.222.184 () {42 vars in 752 bytes} [Thu Jul  4 00:23:45 2024] GET /static/drf-yasg/insQ.min.js => generated 5914 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js
[pid: 4398|app: 0|req: 133/133] 218.159.222.184 () {42 vars in 802 bytes} [Thu Jul  4 00:23:45 2024] GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js => generated 6014 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js
[pid: 4398|app: 0|req: 134/134] 218.159.222.184 () {42 vars in 824 bytes} [Thu Jul  4 00:23:45 2024] GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js => generated 6058 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/immutable.min.js
[pid: 4398|app: 0|req: 135/135] 218.159.222.184 () {42 vars in 762 bytes} [Thu Jul  4 00:23:45 2024] GET /static/drf-yasg/immutable.min.js => generated 5934 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui.css
[pid: 4398|app: 0|req: 136/136] 218.159.222.184 () {42 vars in 805 bytes} [Thu Jul  4 00:23:45 2024] GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css => generated 5990 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/drf-yasg/swagger-ui-init.js
[pid: 4398|app: 0|req: 137/137] 218.159.222.184 () {42 vars in 766 bytes} [Thu Jul  4 00:23:45 2024] GET /static/drf-yasg/swagger-ui-init.js => generated 5942 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 138/138] 218.159.222.184 () {42 vars in 831 bytes} [Thu Jul  4 00:24:19 2024] GET /admin/ => generated 11794 bytes in 15 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
Not Found: /static/admin/css/dashboard.css
[pid: 4398|app: 0|req: 139/139] 218.159.222.184 () {42 vars in 771 bytes} [Thu Jul  4 00:24:19 2024] GET /static/admin/css/dashboard.css => generated 5926 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/responsive.css
[pid: 4398|app: 0|req: 140/140] 218.159.222.184 () {42 vars in 773 bytes} [Thu Jul  4 00:24:19 2024] GET /static/admin/css/responsive.css => generated 5930 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/nav_sidebar.css
[pid: 4398|app: 0|req: 141/141] 218.159.222.184 () {42 vars in 775 bytes} [Thu Jul  4 00:24:19 2024] GET /static/admin/css/nav_sidebar.css => generated 5934 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/base.css
[pid: 4398|app: 0|req: 142/142] 218.159.222.184 () {42 vars in 761 bytes} [Thu Jul  4 00:24:19 2024] GET /static/admin/css/base.css => generated 5906 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/css/dark_mode.css
[pid: 4398|app: 0|req: 143/143] 218.159.222.184 () {42 vars in 771 bytes} [Thu Jul  4 00:24:19 2024] GET /static/admin/css/dark_mode.css => generated 5926 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/theme.js
[pid: 4398|app: 0|req: 144/144] 218.159.222.184 () {42 vars in 744 bytes} [Thu Jul  4 00:24:19 2024] GET /static/admin/js/theme.js => generated 5902 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /static/admin/js/nav_sidebar.js
[pid: 4398|app: 0|req: 145/145] 218.159.222.184 () {42 vars in 756 bytes} [Thu Jul  4 00:24:19 2024] GET /static/admin/js/nav_sidebar.js => generated 5926 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 146/146] 218.159.222.184 () {44 vars in 862 bytes} [Thu Jul  4 00:32:54 2024] GET /admin/ => generated 11794 bytes in 15 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 147/147] 218.159.222.184 () {46 vars in 893 bytes} [Thu Jul  4 00:32:57 2024] GET /admin/ => generated 11794 bytes in 15 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 148/148] 218.159.222.184 () {46 vars in 897 bytes} [Thu Jul  4 00:32:59 2024] GET /swagger/ => generated 2417 bytes in 5 msecs (HTTP/1.1 200) 8 headers in 257 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 149/149] 218.159.222.184 () {48 vars in 906 bytes} [Thu Jul  4 00:33:00 2024] GET /swagger/?format=openapi => generated 7994 bytes in 17 msecs (HTTP/1.1 200) 8 headers in 272 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 150/150] 44.196.175.104 () {36 vars in 471 bytes} [Thu Jul  4 00:33:01 2024] GET /swagger/?format=openapi => generated 7994 bytes in 13 msecs (HTTP/1.1 200) 8 headers in 272 bytes (1 switches on core 0)
Not Found: /
[pid: 4398|app: 0|req: 151/151] 211.231.103.105 () {40 vars in 521 bytes} [Thu Jul  4 00:33:38 2024] GET / => generated 5544 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /
[pid: 4398|app: 0|req: 152/152] 27.0.238.186 () {40 vars in 551 bytes} [Thu Jul  4 00:33:39 2024] GET / => generated 5544 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /
[pid: 4398|app: 0|req: 153/153] 122.47.151.227 () {40 vars in 674 bytes} [Thu Jul  4 00:33:58 2024] GET / => generated 5544 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 154/154] 211.231.103.107 () {40 vars in 537 bytes} [Thu Jul  4 00:34:04 2024] GET /swagger/ => generated 2189 bytes in 2 msecs (HTTP/1.1 200) 8 headers in 257 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 155/155] 211.231.103.104 () {40 vars in 546 bytes} [Thu Jul  4 00:34:04 2024] GET /swagger/ => generated 2189 bytes in 2 msecs (HTTP/1.1 200) 8 headers in 257 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 156/156] 211.231.103.106 () {40 vars in 570 bytes} [Thu Jul  4 00:34:05 2024] GET /swagger/ => generated 2189 bytes in 2 msecs (HTTP/1.1 200) 8 headers in 257 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 4398|app: 0|req: 157/157] 122.47.151.227 () {38 vars in 519 bytes} [Thu Jul  4 00:34:05 2024] GET /favicon.ico => generated 5595 bytes in 7 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /apple-touch-icon.png
[pid: 4398|app: 0|req: 158/158] 122.47.151.227 () {38 vars in 537 bytes} [Thu Jul  4 00:34:05 2024] GET /apple-touch-icon.png => generated 5622 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /apple-touch-icon-precomposed.png
[pid: 4398|app: 0|req: 159/159] 122.47.151.227 () {38 vars in 561 bytes} [Thu Jul  4 00:34:05 2024] GET /apple-touch-icon-precomposed.png => generated 5658 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /apple-touch-icon-precomposed.png
[pid: 4398|app: 0|req: 160/160] 122.47.151.227 () {38 vars in 561 bytes} [Thu Jul  4 00:34:05 2024] GET /apple-touch-icon-precomposed.png => generated 5658 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 4398|app: 0|req: 161/161] 122.47.151.227 () {38 vars in 519 bytes} [Thu Jul  4 00:34:05 2024] GET /favicon.ico => generated 5595 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /apple-touch-icon.png
[pid: 4398|app: 0|req: 162/162] 122.47.151.227 () {38 vars in 537 bytes} [Thu Jul  4 00:34:05 2024] GET /apple-touch-icon.png => generated 5622 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /
[pid: 4398|app: 0|req: 163/163] 122.47.151.227 () {40 vars in 688 bytes} [Thu Jul  4 00:34:05 2024] GET / => generated 5544 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /
[pid: 4398|app: 0|req: 164/164] 122.47.151.227 () {40 vars in 688 bytes} [Thu Jul  4 00:34:05 2024] GET / => generated 5544 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /robots.txt
[pid: 4398|app: 0|req: 165/165] 34.64.82.74 () {36 vars in 506 bytes} [Thu Jul  4 00:34:08 2024] GET /robots.txt => generated 5592 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 166/166] 122.47.151.227 () {40 vars in 690 bytes} [Thu Jul  4 00:34:08 2024] GET /swagger/ => generated 2189 bytes in 2 msecs (HTTP/1.1 200) 8 headers in 257 bytes (1 switches on core 0)
Not Found: /
[pid: 4398|app: 0|req: 167/167] 34.64.82.67 () {38 vars in 630 bytes} [Thu Jul  4 00:34:08 2024] GET / => generated 5544 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 168/168] 122.47.151.227 () {42 vars in 771 bytes} [Thu Jul  4 00:34:08 2024] GET /swagger/?format=openapi => generated 7994 bytes in 13 msecs (HTTP/1.1 200) 8 headers in 272 bytes (1 switches on core 0)
Not Found: /
[pid: 4398|app: 0|req: 169/169] 34.64.82.75 () {38 vars in 504 bytes} [Thu Jul  4 00:34:09 2024] GET / => generated 5544 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 170/170] 44.196.175.104 () {36 vars in 471 bytes} [Thu Jul  4 00:34:10 2024] GET /swagger/?format=openapi => generated 7994 bytes in 12 msecs (HTTP/1.1 200) 8 headers in 272 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 4398|app: 0|req: 171/171] 34.64.82.69 () {38 vars in 473 bytes} [Thu Jul  4 00:34:13 2024] GET /favicon.ico => generated 5595 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 172/172] 122.47.151.227 () {40 vars in 690 bytes} [Thu Jul  4 00:34:19 2024] GET /swagger/ => generated 2189 bytes in 3 msecs (HTTP/1.1 200) 8 headers in 257 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 173/173] 122.47.151.227 () {42 vars in 771 bytes} [Thu Jul  4 00:34:19 2024] GET /swagger/?format=openapi => generated 7994 bytes in 13 msecs (HTTP/1.1 200) 8 headers in 272 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 174/174] 44.196.175.104 () {36 vars in 471 bytes} [Thu Jul  4 00:34:20 2024] GET /swagger/?format=openapi => generated 7994 bytes in 12 msecs (HTTP/1.1 200) 8 headers in 272 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 175/175] 122.47.151.227 () {40 vars in 690 bytes} [Thu Jul  4 00:35:48 2024] GET /swagger/ => generated 2189 bytes in 3 msecs (HTTP/1.1 200) 8 headers in 257 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 176/176] 122.47.151.227 () {42 vars in 771 bytes} [Thu Jul  4 00:35:48 2024] GET /swagger/?format=openapi => generated 7994 bytes in 15 msecs (HTTP/1.1 200) 8 headers in 272 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 177/177] 44.196.175.104 () {36 vars in 471 bytes} [Thu Jul  4 00:35:49 2024] GET /swagger/?format=openapi => generated 7994 bytes in 12 msecs (HTTP/1.1 200) 8 headers in 272 bytes (1 switches on core 0)
Not Found: /
[pid: 4398|app: 0|req: 178/178] 27.0.238.68 () {40 vars in 539 bytes} [Thu Jul  4 00:36:17 2024] GET / => generated 5544 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 179/179] 27.0.238.117 () {40 vars in 556 bytes} [Thu Jul  4 00:36:17 2024] GET /swagger/ => generated 2189 bytes in 2 msecs (HTTP/1.1 200) 8 headers in 257 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 180/180] 218.159.222.184 () {46 vars in 893 bytes} [Thu Jul  4 00:52:08 2024] GET /admin/ => generated 11794 bytes in 15 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 181/181] 218.159.222.184 () {44 vars in 901 bytes} [Thu Jul  4 00:52:10 2024] GET /admin/workhol/post/ => generated 10576 bytes in 18 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 182/182] 218.159.222.184 () {42 vars in 735 bytes} [Thu Jul  4 00:52:10 2024] GET /admin/jsi18n/ => generated 9861 bytes in 4 msecs (HTTP/1.1 200) 7 headers in 230 bytes (1 switches on core 0)
Internal Server Error: /admin/workhol/post/2/change/
Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: workhol_myuser.point

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/boundfield.py", line 108, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/contrib/admin/widgets.py", line 327, in get_context
    "rendered_widget": self.widget.render(name, value, attrs),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 764, in get_context
    context = super().get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 715, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 655, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/models.py", line 1422, in __iter__
    for obj in queryset:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 518, in _iterator
    yield from iterable
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: workhol_myuser.point
[pid: 4398|app: 0|req: 183/183] 218.159.222.184 () {44 vars in 932 bytes} [Thu Jul  4 00:52:12 2024] GET /admin/workhol/post/2/change/ => generated 631739 bytes in 213 msecs (HTTP/1.1 500) 7 headers in 243 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 184/184] 218.159.222.184 () {44 vars in 901 bytes} [Thu Jul  4 00:52:21 2024] GET /admin/workhol/post/ => generated 10576 bytes in 17 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 185/185] 218.159.222.184 () {46 vars in 893 bytes} [Thu Jul  4 00:52:25 2024] GET /admin/ => generated 11794 bytes in 16 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
Internal Server Error: /intern/community/
Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'Post' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 236, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'author'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: workhol_myuser.point

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/likelion_team5/likelion_inha_team5/likelion_inha_team5/workhol/views.py", line 223, in post_list
    return render(request, 'workhol/post_list.html', {'posts': posts, 'site_name': site_name, 'category_name': category_name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 254, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 217, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: workhol_myuser.point
[pid: 4398|app: 0|req: 186/186] 218.159.222.184 () {42 vars in 853 bytes} [Thu Jul  4 00:52:35 2024] GET /intern/community/ => generated 250119 bytes in 74 msecs (HTTP/1.1 500) 7 headers in 243 bytes (1 switches on core 0)
Internal Server Error: /intern/community/
Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'Post' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 236, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'author'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: workhol_myuser.point

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/likelion_team5/likelion_inha_team5/likelion_inha_team5/workhol/views.py", line 223, in post_list
    return render(request, 'workhol/post_list.html', {'posts': posts, 'site_name': site_name, 'category_name': category_name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 254, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 217, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: workhol_myuser.point
[pid: 4398|app: 0|req: 187/187] 218.159.222.184 () {44 vars in 884 bytes} [Thu Jul  4 00:59:06 2024] GET /intern/community/ => generated 250256 bytes in 71 msecs (HTTP/1.1 500) 7 headers in 243 bytes (1 switches on core 0)
Internal Server Error: /intern/community/
Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'Post' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 236, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'author'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: workhol_myuser.point

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/likelion_team5/likelion_inha_team5/likelion_inha_team5/workhol/views.py", line 223, in post_list
    return render(request, 'workhol/post_list.html', {'posts': posts, 'site_name': site_name, 'category_name': category_name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 254, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 217, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: workhol_myuser.point
[pid: 4398|app: 0|req: 188/188] 218.159.222.184 () {44 vars in 884 bytes} [Thu Jul  4 00:59:08 2024] GET /intern/community/ => generated 250256 bytes in 73 msecs (HTTP/1.1 500) 7 headers in 243 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 189/189] 218.159.222.184 () {44 vars in 901 bytes} [Thu Jul  4 00:59:10 2024] GET /admin/workhol/post/ => generated 10576 bytes in 16 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 190/190] 218.159.222.184 () {44 vars in 914 bytes} [Thu Jul  4 00:59:15 2024] GET /admin/workhol/post/ => generated 10576 bytes in 17 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 191/191] 218.159.222.184 () {42 vars in 735 bytes} [Thu Jul  4 00:59:15 2024] GET /admin/jsi18n/ => generated 9861 bytes in 4 msecs (HTTP/1.1 200) 7 headers in 230 bytes (1 switches on core 0)
Internal Server Error: /admin/workhol/post/2/change/
Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: workhol_myuser.point

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/boundfield.py", line 108, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/contrib/admin/widgets.py", line 327, in get_context
    "rendered_widget": self.widget.render(name, value, attrs),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 764, in get_context
    context = super().get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 715, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 655, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/models.py", line 1422, in __iter__
    for obj in queryset:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 518, in _iterator
    yield from iterable
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: workhol_myuser.point
[pid: 4398|app: 0|req: 192/192] 218.159.222.184 () {44 vars in 932 bytes} [Thu Jul  4 00:59:16 2024] GET /admin/workhol/post/2/change/ => generated 631739 bytes in 198 msecs (HTTP/1.1 500) 7 headers in 243 bytes (1 switches on core 0)
Internal Server Error: /admin/workhol/post/2/change/
Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: workhol_myuser.point

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/boundfield.py", line 108, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/contrib/admin/widgets.py", line 327, in get_context
    "rendered_widget": self.widget.render(name, value, attrs),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 764, in get_context
    context = super().get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 715, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 655, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/models.py", line 1422, in __iter__
    for obj in queryset:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 518, in _iterator
    yield from iterable
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: workhol_myuser.point
[pid: 4398|app: 0|req: 193/193] 218.159.222.184 () {46 vars in 963 bytes} [Thu Jul  4 01:00:36 2024] GET /admin/workhol/post/2/change/ => generated 631876 bytes in 196 msecs (HTTP/1.1 500) 7 headers in 243 bytes (2 switches on core 0)
Internal Server Error: /admin/workhol/post/2/change/
Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: workhol_myuser.point

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/boundfield.py", line 108, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/contrib/admin/widgets.py", line 327, in get_context
    "rendered_widget": self.widget.render(name, value, attrs),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 764, in get_context
    context = super().get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 715, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 655, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/models.py", line 1422, in __iter__
    for obj in queryset:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 518, in _iterator
    yield from iterable
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: workhol_myuser.point
[pid: 4398|app: 0|req: 194/194] 218.159.222.184 () {46 vars in 963 bytes} [Thu Jul  4 01:00:38 2024] GET /admin/workhol/post/2/change/ => generated 631876 bytes in 191 msecs (HTTP/1.1 500) 7 headers in 243 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 195/195] 218.159.222.184 () {44 vars in 914 bytes} [Thu Jul  4 01:05:33 2024] GET /admin/workhol/post/ => generated 10576 bytes in 18 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
Internal Server Error: /admin/workhol/post/2/change/
Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: workhol_myuser.point

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/boundfield.py", line 108, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/contrib/admin/widgets.py", line 327, in get_context
    "rendered_widget": self.widget.render(name, value, attrs),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 764, in get_context
    context = super().get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 715, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 655, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/models.py", line 1422, in __iter__
    for obj in queryset:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 518, in _iterator
    yield from iterable
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: workhol_myuser.point
[pid: 4398|app: 0|req: 196/196] 218.159.222.184 () {44 vars in 932 bytes} [Thu Jul  4 01:05:37 2024] GET /admin/workhol/post/2/change/ => generated 631739 bytes in 191 msecs (HTTP/1.1 500) 7 headers in 243 bytes (1 switches on core 0)
Not Found: /
[pid: 4398|app: 0|req: 197/197] 36.134.147.75 () {44 vars in 807 bytes} [Thu Jul  4 01:07:02 2024] GET / => generated 5544 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Internal Server Error: /intern/community/
Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'Post' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 236, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'author'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: workhol_myuser.point

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/likelion_team5/likelion_inha_team5/likelion_inha_team5/workhol/views.py", line 223, in post_list
    return render(request, 'workhol/post_list.html', {'posts': posts, 'site_name': site_name, 'category_name': category_name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 254, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 217, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: workhol_myuser.point
[pid: 4398|app: 0|req: 198/198] 218.159.222.184 () {42 vars in 853 bytes} [Thu Jul  4 01:13:35 2024] GET /intern/community/ => generated 250119 bytes in 73 msecs (HTTP/1.1 500) 7 headers in 243 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 199/199] 3.254.77.104 () {36 vars in 434 bytes} [Thu Jul  4 01:14:45 2024] GET /.git/config => generated 0 bytes in 6 msecs (HTTP/1.1 301) 5 headers in 203 bytes (1 switches on core 0)
Internal Server Error: /intern/community/
Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'Post' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 236, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'author'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: workhol_myuser.point

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/likelion_team5/likelion_inha_team5/likelion_inha_team5/workhol/views.py", line 223, in post_list
    return render(request, 'workhol/post_list.html', {'posts': posts, 'site_name': site_name, 'category_name': category_name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 254, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 217, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: workhol_myuser.point
[pid: 4398|app: 0|req: 200/200] 218.159.222.184 () {44 vars in 884 bytes} [Thu Jul  4 01:19:39 2024] GET /intern/community/ => generated 250256 bytes in 72 msecs (HTTP/1.1 500) 7 headers in 243 bytes (1 switches on core 0)
Internal Server Error: /intern/community/
Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'Post' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 236, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'author'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: workhol_myuser.point

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/likelion_team5/likelion_inha_team5/likelion_inha_team5/workhol/views.py", line 223, in post_list
    return render(request, 'workhol/post_list.html', {'posts': posts, 'site_name': site_name, 'category_name': category_name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 254, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 217, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: workhol_myuser.point
[pid: 4398|app: 0|req: 201/201] 218.159.222.184 () {44 vars in 884 bytes} [Thu Jul  4 01:19:40 2024] GET /intern/community/ => generated 250256 bytes in 76 msecs (HTTP/1.1 500) 7 headers in 243 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 202/202] 218.159.222.184 () {46 vars in 893 bytes} [Thu Jul  4 01:19:45 2024] GET /admin/ => generated 11794 bytes in 15 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 203/203] 218.159.222.184 () {44 vars in 901 bytes} [Thu Jul  4 01:19:47 2024] GET /admin/workhol/post/ => generated 10576 bytes in 16 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 204/204] 218.159.222.184 () {42 vars in 735 bytes} [Thu Jul  4 01:19:47 2024] GET /admin/jsi18n/ => generated 9861 bytes in 4 msecs (HTTP/1.1 200) 7 headers in 230 bytes (1 switches on core 0)
Internal Server Error: /admin/workhol/post/2/change/
Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: workhol_myuser.point

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/template/base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/boundfield.py", line 108, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/contrib/admin/widgets.py", line 327, in get_context
    "rendered_widget": self.widget.render(name, value, attrs),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 764, in get_context
    context = super().get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 715, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/widgets.py", line 655, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/forms/models.py", line 1422, in __iter__
    for obj in queryset:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 518, in _iterator
    yield from iterable
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dasol/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: workhol_myuser.point
[pid: 4398|app: 0|req: 205/205] 218.159.222.184 () {44 vars in 932 bytes} [Thu Jul  4 01:19:48 2024] GET /admin/workhol/post/2/change/ => generated 631739 bytes in 192 msecs (HTTP/1.1 500) 7 headers in 243 bytes (2 switches on core 0)
[pid: 4398|app: 0|req: 206/206] 218.159.222.184 () {46 vars in 963 bytes} [Thu Jul  4 01:23:14 2024] GET /admin/workhol/post/2/change/ => generated 22737 bytes in 42 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
[pid: 4398|app: 0|req: 207/207] 218.159.222.184 () {42 vars in 744 bytes} [Thu Jul  4 01:23:14 2024] GET /admin/jsi18n/ => generated 9861 bytes in 4 msecs (HTTP/1.1 200) 7 headers in 230 bytes (1 switches on core 0)
